# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-backend-for-this:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: 'yarn'

      - name: Install dependencies and build backend-for-this
        run: cd backend-for-this && yarn install && yarn build

      - run: cd backend-for-this && yarn ci
      - run: cd backend-for-this && yarn run build --if-present
      - run: cd backend-for-this && yarn test

  build-registration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: 'yarn'

      - name: Install dependencies and build registration
        run: cd registration && yarn install && yarn build

      - run: cd registration && yarn ci
      - run: cd registration && yarn run build --if-present
      - run: cd registration && yarn test
